### ISSUE TITLE
Plugin is now working. Is it ready?

### ISSUE THREAD

**Issue by arislaw** [peon374/serverless-plugin-cognito-identity#1]
I installed the plugin using 

`npm install <plugin> --save`

but when I run serverless 

`slss function run`

I got this message:

> ServerlessError: Error loading this plugin: /w/x/y/node_modules/serverless-plugin-cognito-identity

is it ready to use?

tks a lot!

**Comment by peon374** [comment]
No, sorry this is a work in progress.  It is under active development. I expect to have it completed by the 20th.

**Comment by arislaw** [comment]
ok, tks a lot!
